### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by z0z0Official** [palant/autoconnect-comfyui#2]
Traceback (most recent call last):
  File "C:\ComfyUI Rebuild Rebuild\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1798, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ComfyUI Rebuild Rebuild\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\autoconnect-comfyui\\__init__.py'

Cannot import C:\ComfyUI Rebuild Rebuild\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\autoconnect-comfyui module for custom nodes: [Errno 2] No such file or directory: 'C:\\ComfyUI Rebuild Rebuild\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\autoconnect-comfyui\\__init__.py'

**Comment by palant** [comment]
Please see my reply here: https://github.com/palant/autoconnect-comfyui/issues/1#issuecomment-1826257001
